services:
  meilisearch:
    container_name: django_react_starter_meilisearch
    image: getmeili/meilisearch:v1.11.0
    environment:
      - MEILI_MASTER_KEY=nje#_zn0wfh49m9_&8sd10cr&i51^na3fn61fkdbs*ol21doz(
    networks:
      - django_meilisearch_indexer
    ports:
      - "7700:7700"
    volumes:
      - ./data/meilisearch:/meili_data

networks:
  django_meilisearch_indexer:
    driver: bridge
