name: Tests

on:
  workflow_call:
  # The "on push" event is necessary for the README badges
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: |
            ./uv.lock

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: python-${{ matrix.python-version }}-venv-${{ hashFiles('./uv.lock') }}

      - name: Install dependencies
        if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --frozen

  tests:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    services:
      meilisearch:
        image: getmeili/meilisearch:v1.11.0
        env:
          MEILI_HTTP_ADDR: 0.0.0.0:7700
          MEILI_MASTER_KEY: meilisearch_local_master_key
        ports:
          - 7700:7700
        options: --health-cmd="curl -f http://localhost:7700/health" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: |
            ./uv.lock

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: python-${{ matrix.python-version }}-venv-${{ hashFiles('./uv.lock') }}

      - name: Run tests
        run: |
          . .venv/bin/activate
          python -m unittest discover .
